<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
    <!ELEMENT root (menu)>
    <!ELEMENT menu (item+)>
    <!ELEMENT item (name, price, description)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
]>
<?xml-stylesheet type="text/css" href="style.css"?>
<root>
    <menu>
        <item>
            <name>Beetroot and feta salad</name>
            <price>$15.00</price>
            <description>Suitable for vegetarians, made with fresh beetroot</description>
        </item>
        <item>
            <name>Sourdough Rye Sandwich</name>
            <price>$18.00</price>
            <description>Cheese and salad sandwich made with organic, sourdough rye bread</description>
        </item>
        <item>
            <name>Spinach Pie and Salad</name>
            <price>$20.00</price>
            <description>Tasty pie with salad</description>
        </item>
    </menu>
</root>
